import streamlit as st
from serpapi import GoogleSearch
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.pipeline import make_pipeline

# Sample labeled dataset for demonstration
# In a real scenario, you would have a larger, more diverse dataset
training_data = [
("software engineer", "IT software engineer job"),
("data scientist", "data scientist job"),
("teacher", "Education teacher job"),
("nurse", "Healthcare nurse job"),
("marketing manager", "Marketing marketing manager job"),
("customer support", "Customer support customer support job"),
("chef", "Culinary chef job"),
("electrician", "Skilled trades electrician job"),
("graphic designer", "Design graphic designer job"),
("mechanical engineer", "Engineering mechanical engineer job"),
("accountant", "Finance accountant job"),
("human resources", "Human Resources HR job"),
("sales representative", "Sales sales representative job"),
("research scientist", "Research research scientist job"),
("project manager", "Project Management project manager job"),
("web developer", "IT web developer job"),
("pharmacist", "Healthcare pharmacist job"),
("architect", "Architecture architect job"),
("lawyer", "Legal lawyer job"),
("data analyst", "Data Analysis data analyst job"),
("customer service representative", "Customer service customer service representative job"),
("product manager", "Product Management product manager job"),
("network engineer", "IT network engineer job"),
("psychologist", "Healthcare psychologist job"),
("mechanic", "Skilled trades mechanic job"),
("public relations specialist", "Public Relations public relations specialist job"),
("biomedical engineer", "Engineering biomedical engineer job"),
("financial analyst", "Finance financial analyst job"),
("human resources manager", "Human Resources human resources manager job"),
("real estate agent", "Real Estate real estate agent job"),
("software developer", "IT software developer job"),
("physical therapist", "Healthcare physical therapist job"),
("plumber", "Skilled trades plumber job"),
("social media manager", "Social Media social media manager job"),
("civil engineer", "Engineering civil engineer job"),
("account executive", "Sales account executive job"),
("environmental scientist", "Science environmental scientist job"),
("UX/UI designer", "Design UX/UI designer job"),
("industrial engineer", "Engineering industrial engineer job"),
("investment banker", "Finance investment banker job"),
("training coordinator", "Human Resources training coordinator job"),
("marketing coordinator", "Marketing marketing coordinator job"),
("software architect", "IT software architect job"),
("registered nurse", "Healthcare registered nurse job"),
("carpenter", "Skilled trades carpenter job"),
("journalist", "Media journalist job"),
("mechatronics engineer", "Engineering mechatronics engineer job"),
("business analyst", "Business business analyst job"),
("sales manager", "Sales sales manager job"),
("biotechnologist", "Science biotechnologist job"),
("art director", "Design art director job"),
("electrical engineer", "Engineering electrical engineer job"),
("accounting manager", "Finance accounting manager job"),
("HR specialist", "Human Resources HR specialist job"),
("insurance agent", "Insurance insurance agent job"),
("game developer", "IT game developer job"),
("radiologist", "Healthcare radiologist job"),
("welder", "Skilled trades welder job"),
("content creator", "Media content creator job"),
("aerospace engineer", "Engineering aerospace engineer job"),
("sales associate", "Sales sales associate job"),
("chemist", "Science chemist job"),
("interior designer", "Design interior designer job"),
("mechanical technician", "Engineering mechanical technician job"),
("financial planner", "Finance financial planner job"),
("recruiter", "Human Resources recruiter job"),
("digital marketer", "Marketing digital marketer job"),
("systems analyst", "IT systems analyst job"),
("phlebotomist", "Healthcare phlebotomist job"),
("plumber apprentice", "Skilled trades plumber apprentice job"),
("copywriter", "Media copywriter job"),
("chemical engineer", "Engineering chemical engineer job"),
("financial analyst", "Finance financial analyst job"),
("HR generalist", "Human Resources HR generalist job"),
("real estate broker", "Real Estate real estate broker job"),
("software tester", "IT software tester job"),
("occupational therapist", "Healthcare occupational therapist job"),
("construction worker", "Skilled trades construction worker job"),
("video editor", "Media video editor job"),
("environmental engineer", "Engineering environmental engineer job"),
("bank teller", "Finance bank teller job"),
("training specialist", "Human Resources training specialist job"),
("social media coordinator", "Marketing social media coordinator job"),
("data engineer", "IT data engineer job"),
("emergency room nurse", "Healthcare emergency room nurse job"),
("HVAC technician", "Skilled trades HVAC technician job"),
("reporter", "Media reporter job"),
("materials engineer", "Engineering materials engineer job"),
("investment analyst", "Finance investment analyst job"),
("talent acquisition specialist", "Human Resources talent acquisition specialist job"),
("event coordinator", "Marketing event coordinator job"),
("cloud architect", "IT cloud architect job"),
("registered dietitian", "Healthcare registered dietitian job"),
("auto mechanic", "Skilled trades auto mechanic job"),
("web designer", "Design web designer job"),
("quality engineer", "Engineering quality engineer job"),
("actuary", "Finance actuary job"),
("HR coordinator", "Human Resources HR coordinator job"),
("insurance underwriter", "Insurance insurance underwriter job"),
("DevOps engineer", "IT DevOps engineer job"),
("surgical nurse", "Healthcare surgical nurse job"),
("plumbing apprentice", "Skilled trades plumbing apprentice job"),
("editor", "Media editor job"),
("mechanical design engineer", "Engineering mechanical design engineer job"),
("accounting clerk", "Finance accounting clerk job"),
("HR assistant", "Human Resources HR assistant job"),
("real estate appraiser", "Real Estate real estate appraiser job"),
("front-end developer", "IT front-end developer job"),
("physical therapy assistant", "Healthcare physical therapy assistant job"),
("machinist", "Skilled trades machinist job"),
("social media strategist", "Marketing social media strategist job"),
("data scientist", "Data Analysis data scientist job"),
("UX/UI developer", "Design UX/UI developer job"),
("chemical technician", "Engineering chemical technician job"),
("financial advisor", "Finance financial advisor job"),
("HR director", "Human Resources HR director job"),
("insurance claims adjuster", "Insurance insurance claims adjuster job"),
("database administrator", "IT database administrator job"),
("family nurse practitioner", "Healthcare family nurse practitioner job"),
("carpenter apprentice", "Skilled trades carpenter apprentice job"),
("journalism intern", "Media journalism intern job"),
("aerospace engineering technician", "Engineering aerospace engineering technician job"),
("investment banking analyst", "Finance investment banking analyst job"),
("HR manager", "Human Resources HR manager job"),
("real estate developer", "Real Estate real estate developer job"),
("software engineer intern", "IT software engineer intern job"),
("clinical pharmacist", "Healthcare clinical pharmacist job"),
("welding inspector", "Skilled trades welding inspector job"),
("freelance writer", "Media freelance writer job"),
("civil engineering technician", "Engineering civil engineering technician job"),
("accounting consultant", "Finance accounting consultant job"),
("HR specialist", "Human Resources HR specialist job"),
("real estate agent assistant", "Real Estate real estate agent assistant job"),
("QA engineer", "IT QA engineer job"),
("emergency room nurse practitioner", "Healthcare emergency room nurse practitioner job"),
("electrician apprentice", "Skilled trades electrician apprentice job"),
("social media influencer", "Marketing social media influencer job"),
("data engineer", "Data Analysis data engineer job"),
("architectural designer", "Design architectural designer job"),
("environmental scientist intern", "Science environmental scientist intern job"),
("investment banker analyst", "Finance investment banker analyst job"),
("HR consultant", "Human Resources HR consultant job"),
("insurance sales agent", "Insurance insurance sales agent job"),
("systems administrator", "IT systems administrator job"),
("psychiatric nurse", "Healthcare psychiatric nurse job"),
("carpenter journeyman", "Skilled trades carpenter journeyman job"),
("reporter intern", "Media reporter intern job"),
("biomedical engineering technician", "Engineering biomedical engineering technician job"),
("financial analyst intern", "Finance financial analyst intern job"),
("HR generalist", "Human Resources HR generalist job"),
("real estate agent trainee", "Real Estate real estate agent trainee job"),
("software developer intern", "IT software developer intern job"),
("clinical research pharmacist", "Healthcare clinical research pharmacist job"),
("pipefitter", "Skilled trades pipefitter job"),
("content strategist", "Marketing content strategist job"),
("data scientist intern", "Data Analysis data scientist intern job"),
("UI/UX designer", "Design UI/UX designer job"),
("civil engineering intern", "Engineering civil engineering intern job"),
("financial consultant", "Finance financial consultant job"),
("HR intern", "Human Resources HR intern job"),
("insurance underwriting assistant", "Insurance insurance underwriting assistant job"),
("IT support specialist", "IT IT support specialist job"),
("pediatric nurse", "Healthcare pediatric nurse job"),
("HVAC apprentice", "Skilled trades HVAC apprentice job"),
("journalism editor", "Media journalism editor job"),
("aerospace engineering intern", "Engineering aerospace engineering intern job"),
("investment banking associate", "Finance investment banking associate job"),
("HR recruiter", "Human Resources HR recruiter job"),
("real estate agent intern", "Real Estate real estate agent intern job"),
("software quality assurance engineer", "IT software quality assurance engineer job"),
("clinical pharmacist specialist", "Healthcare clinical pharmacist specialist job"),
("welding engineer", "Skilled trades welding engineer job"),
("creative writer", "Media creative writer job"),
("civil engineering technician intern", "Engineering civil engineering technician intern job"),
("accounting manager intern", "Finance accounting manager intern job"),
("HR specialist intern", "Human Resources HR specialist intern job"),
("real estate analyst", "Real Estate real estate analyst job"),
("QA analyst", "IT QA analyst job"),
("emergency room nurse intern", "Healthcare emergency room nurse intern job"),
("electrician apprentice intern", "Skilled trades electrician apprentice intern job"),
("social media manager intern", "Marketing social media manager intern job"),
("data analyst intern", "Data Analysis data analyst intern job"),
("architectural designer intern", "Design architectural designer intern job"),
("environmental scientist intern", "Science environmental scientist intern job"),
("investment analyst intern", "Finance investment analyst intern job"),
("HR assistant intern", "Human Resources HR assistant intern job"),
("insurance agent intern", "Insurance insurance agent intern job"),
("IT support specialist intern", "IT IT support specialist intern job"),
("pediatric nurse intern", "Healthcare pediatric nurse intern job"),
("HVAC apprentice intern", "Skilled trades HVAC apprentice intern job"),
("journalism editor intern", "Media journalism editor intern job"),
("aerospace engineering intern", "Engineering aerospace engineering intern job"),
("investment banking associate intern", "Finance investment banking associate intern job"),
("HR recruiter intern", "Human Resources HR recruiter intern job"),
("real estate analyst intern", "Real Estate real estate analyst intern job"),
("software quality assurance engineer intern", "IT software quality assurance engineer intern job"),
("clinical pharmacist specialist intern", "Healthcare clinical pharmacist specialist intern job"),
("welding engineer intern", "Skilled trades welding engineer intern job"),
("creative writer intern", "Media creative writer intern job"),
("civil engineering technician intern", "Engineering civil engineering technician intern job"),
("accounting manager intern", "Finance accounting manager intern job"),
("HR specialist intern", "Human Resources HR specialist intern job"),
("real estate analyst intern", "Real Estate real estate analyst intern job"),
("QA analyst intern", "IT QA analyst intern job"),
("emergency room nurse intern", "Healthcare emergency room nurse intern job"),
("electrician apprentice intern", "Skilled trades electrician apprentice intern job"),
("social media manager intern", "Marketing social media manager intern job"),
("data analyst intern", "Data Analysis data analyst intern job"),
("architectural designer intern", "Design architectural designer intern job"),
("environmental scientist intern", "Science environmental scientist intern job"),
("investment analyst intern", "Finance investment analyst intern job"),
("HR assistant intern", "Human Resources HR assistant intern job"),
("insurance agent intern", "Insurance insurance agent intern job"),
("IT support specialist intern", "IT IT support specialist intern job"),
("pediatric nurse intern", "Healthcare pediatric nurse intern job"),
("HVAC apprentice intern", "Skilled trades HVAC apprentice intern job"),
("journalism editor intern", "Media journalism editor intern job"),
("aerospace engineering intern", "Engineering aerospace engineering intern job"),
("investment banking associate intern", "Finance investment banking associate intern job"),
("HR recruiter intern", "Human Resources HR recruiter intern job"),
("real estate analyst intern", "Real Estate real estate analyst intern job"),
("software quality assurance engineer intern", "IT software quality assurance engineer intern job"),
("clinical pharmacist specialist intern", "Healthcare clinical pharmacist specialist intern job"),
("welding engineer intern", "Skilled trades welding engineer intern job"),
("creative writer intern", "Media creative writer intern job"),
("civil engineering technician intern", "Engineering civil engineering technician intern job"),
("accounting manager intern", "Finance accounting manager intern job"),
("HR specialist intern", "Human Resources HR specialist intern job"),
("cybersecurity analyst", "IT cybersecurity analyst job"),    
("pharmaceutical researcher", "Science pharmaceutical researcher job"),
("logistics coordinator", "Logistics logistics coordinator job"),
("financial controller", "Finance financial controller job"),
("UX/UI designer", "Design UX/UI designer job"),
("software quality assurance engineer", "IT software quality assurance engineer job"),
("occupational therapist", "Healthcare occupational therapist job"),
("construction project manager", "Construction construction project manager job"),
("social media strategist", "Marketing social media strategist job"),
("mechanical design engineer", "Engineering mechanical design engineer job"),
("business intelligence analyst", "Business business intelligence analyst job"),
("real estate agent", "Real Estate real estate agent job"),
("mobile app developer", "IT mobile app developer job"),
("clinical psychologist", "Healthcare clinical psychologist job"),
("carpenter apprentice", "Skilled trades carpenter apprentice job"),
("content creator", "Media content creator job"),
("quantum physicist", "Science quantum physicist job"),
("operations manager", "Management operations manager job"),
("HR business partner", "Human Resources HR business partner job"),
("claims adjuster", "Insurance claims adjuster job"),
("machine learning engineer", "IT machine learning engineer job"),
("emergency room physician", "Healthcare emergency room physician job"),
("welding inspector", "Skilled trades welding inspector job"),
("video editor", "Media video editor job"),
("environmental engineer", "Engineering environmental engineer job"),
("actuary", "Finance actuary job"),
("employee relations specialist", "Human Resources employee relations specialist job"),
("insurance broker", "Insurance insurance broker job"),
("database administrator", "IT database administrator job"),
("radiation therapist", "Healthcare radiation therapist job"),
("electrician apprentice", "Skilled trades electrician apprentice job"),
("technical writer", "Media technical writer job"),
("biomedical engineer", "Engineering biomedical engineer job"),
("financial analyst intern", "Finance financial analyst intern job"),
("training specialist", "Human Resources training specialist job"),
("search engine optimization (SEO) specialist", "Marketing SEO specialist job"),
("cloud solutions architect", "IT cloud solutions architect job"),
("registered dietitian", "Healthcare registered dietitian job"),
("pipefitter", "Skilled trades pipefitter job"),
("copywriter", "Media copywriter job"),
("chemical engineer", "Engineering chemical engineer job"),
("investment advisor", "Finance investment advisor job"),
("talent acquisition specialist", "Human Resources talent acquisition specialist job"),
("event coordinator", "Marketing event coordinator job"),
("systems analyst", "IT systems analyst job"),
("phlebotomist", "Healthcare phlebotomist job"),
("plumber apprentice", "Skilled trades plumber apprentice job"),
("journalist", "Media journalist job"),
("mechatronics engineer", "Engineering mechatronics engineer job"),
("business analyst", "Business business analyst job"),
("sales manager", "Sales sales manager job"),
("biotechnologist", "Science biotechnologist job"),
("art director", "Design art director job"),
("electrical engineer", "Engineering electrical engineer job"),
("accounting manager", "Finance accounting manager job"),
("HR specialist", "Human Resources HR specialist job"),
("insurance agent", "Insurance insurance agent job"),
("game developer", "IT game developer job"),
("radiologist", "Healthcare radiologist job"),
("welder", "Skilled trades welder job"),
("content creator", "Media content creator job"),
("aerospace engineer", "Engineering aerospace engineer job"),
("sales associate", "Sales sales associate job"),
("chemist", "Science chemist job"),
("interior designer", "Design interior designer job"),
("mechanical technician", "Engineering mechanical technician job"),
("financial planner", "Finance financial planner job"),
("recruiter", "Human Resources recruiter job"),
("digital marketer", "Marketing digital marketer job"),
("systems analyst", "IT systems analyst job"),
("phlebotomist", "Healthcare phlebotomist job"),
("plumber apprentice", "Skilled trades plumber apprentice job"),
("copywriter", "Media copywriter job"),
("chemical engineer", "Engineering chemical engineer job"),
("financial analyst", "Finance financial analyst job"),
("HR generalist", "Human Resources HR generalist job"),
("real estate broker", "Real Estate real estate broker job"),
("software tester", "IT software tester job"),
("occupational therapist", "Healthcare occupational therapist job"),
("construction worker", "Skilled trades construction worker job"),
("video editor", "Media video editor job"),
("environmental engineer", "Engineering environmental engineer job"),
("bank teller", "Finance bank teller job"),
("training specialist", "Human Resources training specialist job"),
("social media coordinator", "Marketing social media coordinator job"),
("data engineer", "IT data engineer job"),
("emergency room nurse", "Healthcare emergency room nurse job"),
("HVAC technician", "Skilled trades HVAC technician job"),
("reporter", "Media reporter job"),
("materials engineer", "Engineering materials engineer job"),
("investment analyst", "Finance investment analyst job"),
("talent acquisition specialist", "Human Resources talent acquisition specialist job"),
("event coordinator", "Marketing event coordinator job"),
("cloud architect", "IT cloud architect job"),
("registered nurse", "Healthcare registered nurse job"),
("auto mechanic", "Skilled trades auto mechanic job"),
("web designer", "Design web designer job"),
("quality engineer", "Engineering quality engineer job"),
("actuary", "Finance actuary job"),
("HR coordinator", "Human Resources HR coordinator job"),
("insurance underwriter", "Insurance insurance underwriter job"),
("DevOps engineer", "IT DevOps engineer job"),
("surgical nurse", "Healthcare surgical nurse job"),
("plumbing apprentice", "Skilled trades plumbing apprentice job"),
("editor", "Media editor job"),
("mechanical design engineer", "Engineering mechanical design engineer job"),
("accounting clerk", "Finance accounting clerk job"),
("HR assistant", "Human Resources HR assistant job"),
("real estate appraiser", "Real Estate real estate appraiser job"),
("front-end developer", "IT front-end developer job"),
("physical therapy assistant", "Healthcare physical therapy assistant job"),
("machinist", "Skilled trades machinist job"),
("social media strategist", "Marketing social media strategist job"),
("data scientist", "Data Analysis data scientist job"),
("UX/UI developer", "Design UX/UI developer job"),
("chemical technician", "Engineering chemical technician job"),
("financial advisor", "Finance financial advisor job"),
("HR director", "Human Resources HR director job"),
("insurance claims adjuster", "Insurance insurance claims adjuster job"),
("database administrator", "IT database administrator job"),
("family nurse practitioner", "Healthcare family nurse practitioner job"),
("carpenter apprentice", "Skilled trades carpenter apprentice job"),
("journalism intern", "Media journalism intern job"),
("aerospace engineering technician", "Engineering aerospace engineering technician job"),
("investment banking analyst", "Finance investment banking analyst job"),
("HR manager", "Human Resources HR manager job"),
("real estate developer", "Real Estate real estate developer job"),
("software engineer intern", "IT software engineer intern job"),
("clinical pharmacist", "Healthcare clinical pharmacist job"),
("welding inspector", "Skilled trades welding inspector job"),
("freelance writer", "Media freelance writer job"),
("civil engineering technician", "Engineering civil engineering technician job"),
("accounting consultant", "Finance accounting consultant job"),
("HR specialist", "Human Resources HR specialist job"),
("real estate agent assistant", "Real Estate real estate agent assistant job"),
("QA engineer", "IT QA engineer job"),
("emergency room nurse practitioner", "Healthcare emergency room nurse practitioner job"),
("electrician apprentice", "Skilled trades electrician apprentice job"),
("social media influencer", "Marketing social media influencer job"),
("data engineer", "Data Analysis data engineer job"),
("architectural designer", "Design architectural designer job"),
("environmental scientist intern", "Science environmental scientist intern job"),
("investment banker analyst", "Finance investment banker analyst job"),
("HR consultant", "Human Resources HR consultant job"),
("insurance sales agent", "Insurance insurance sales agent job"),
("systems administrator", "IT systems administrator job"),
("psychiatric nurse", "Healthcare psychiatric nurse job"),
("carpenter journeyman", "Skilled trades carpenter journeyman job"),
("reporter intern", "Media reporter intern job"),
("biomedical engineering technician", "Engineering biomedical engineering technician job"),
("financial analyst intern", "Finance financial analyst intern job"),
("HR generalist", "Human Resources HR generalist job"),
("real estate agent trainee", "Real Estate real estate agent trainee job"),
("software developer intern", "IT software developer intern job"),
("clinical research pharmacist", "Healthcare clinical research pharmacist job"),
("pipefitter", "Skilled trades pipefitter job"),
("content strategist", "Marketing content strategist job"),
("data scientist intern", "Data Analysis data scientist intern job"),
("UI/UX designer", "Design UI/UX designer job"),
("civil engineering intern", "Engineering civil engineering intern job"),
("financial consultant", "Finance financial consultant job"),
("HR intern", "Human Resources HR intern job"),
("insurance underwriting assistant", "Insurance insurance underwriting assistant job"),
("IT support specialist", "IT IT support specialist job"),
("pediatric nurse", "Healthcare pediatric nurse job"),
("HVAC apprentice", "Skilled trades HVAC apprentice job"),
("journalism editor", "Media journalism editor job"),
("aerospace engineering intern", "Engineering aerospace engineering intern job"),
("investment banking associate", "Finance investment banking associate job"),
("HR recruiter", "Human Resources HR recruiter job"),
("real estate agent intern", "Real Estate real estate agent intern job"),
("software quality assurance engineer", "IT software quality assurance engineer job"),
("clinical pharmacist specialist", "Healthcare clinical pharmacist specialist job"),
("welding engineer", "Skilled trades welding engineer job"),
("creative writer", "Media creative writer job"),
("civil engineering technician", "Engineering civil engineering technician job"),
("accounting manager intern", "Finance accounting manager intern job"),
("HR specialist intern", "Human Resources HR specialist intern job"),
("real estate analyst", "Real Estate real estate analyst job"),
("QA analyst", "IT QA analyst job"),
("emergency room nurse intern", "Healthcare emergency room nurse intern job"),
("electrician apprentice intern", "Skilled trades electrician apprentice intern job"),
("social media manager intern", "Marketing social media manager intern job"),
("data analyst intern", "Data Analysis data analyst intern job"),
("architectural designer intern", "Design architectural designer intern job"),
("environmental scientist intern", "Science environmental scientist intern job"),
("investment analyst intern", "Finance investment analyst intern job"),
("HR assistant intern", "Human Resources HR assistant intern job"),
("insurance agent intern", "Insurance insurance agent intern job"),
("IT support specialist intern", "IT IT support specialist intern job"),
("pediatric nurse intern", "Healthcare pediatric nurse intern job"),
("HVAC apprentice intern", "Skilled trades HVAC apprentice intern job"),
("journalism editor intern", "Media journalism editor intern job"),

("investment banking associate intern", "Finance investment banking associate intern job"),
("HR recruiter intern", "Human Resources HR recruiter intern job"),
("real estate analyst intern", "Real Estate real estate analyst intern job"),
("software quality assurance engineer intern", "IT software quality assurance engineer intern job"),
("clinical pharmacist specialist intern","clinical pharmacist specialist intern" ),
("naib qasid","naib qasid job"),
("mali","mali jobs"),






]

    # Add more examples as needed


# Train a simple text classification model
model = make_pipeline(CountVectorizer(), MultinomialNB())
X, y = zip(*training_data)
model.fit(X, y)

def predict_job_category(user_input):
    return model.predict([user_input])[0]

def serpapi_search(query):
    search_params = {
        "q": query,
        "api_key": "2571163e947b2a303758f118289932369c6a27eeb1700b900832492ce6b23b43"
    }
    search = GoogleSearch(search_params)
    result = search.get_dict()
    return result.get("organic_results", [])

def display_serpapi_jobs(serpapi_results):
    for index, result in enumerate(serpapi_results, start=1):
        title = result.get('title', '')
        company = result.get('snippet', '')
        link = result.get('link', '')
        st.write(f"Job {index}:\n|Title: {title}|\nCompany: {company}|\nLink: {link}\n")

def main():
    st.title("Job Search Chatbot")

    job_description = st.text_input("Enter the job description:", key="job_description_input", value="software engineer job")

    if st.button("Search Jobs"):
        predicted_category = predict_job_category(job_description)
        st.write(f"Predicted Job Category: {predicted_category}")

        # Use the predicted job category in the SerpApi search
        serpapi_results = serpapi_search(predicted_category)

        if serpapi_results:
            st.write("Job Search Results:")
            display_serpapi_jobs(serpapi_results)
        else:
            st.write("No job listings found using SerpApi for the given criteria.")

if __name__ == "__main__":
    main()
